name: Nase Project Ci
on:
  push:
    branches: [master]
    pull_requests:
      branches: [master]
jobs:
  build:
    env:
     CI: true
    strategy:
      matrix:
        os: [linux, windows] 
        node-version: [14,16]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }} # node version to install
      - run: npm install
      - run: npm run build --prefix client
      - run: npm  test