name: Nase Project Ci
on:
  push:
    branches: [master]
    pull_requests:
      branches: [master]
jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        os: [linux]
        node-version: ['16']
        mongo-version: [4]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: install mongodb
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongo-version }}
      - name: Install Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }} # node version to install
      - run: npm install
      - run: npm run build --prefix client
      - run: npm  test
